#!/usr/bin/env sh

# PURPOSE
#   To warn committers that the commit message is not in the proper format, for an issue branch. This will help
#   keep the commits in a proper manner.
#
# USAGE
#   Within the root directory of this project, run the following commands:
#       cp git/hooks/commit-msg .git/hooks/commit-msg
#       chmod +x .git/hooks/commit-msg
#

if [ "${COMMIT_PREFIX}" = "" ]; then
    COMMIT_PREFIX="SBA"
fi
branch_name=$(git symbolic-ref --short HEAD | grep -E "^${COMMIT_PREFIX}[-_][0-9]+")
if [ "${branch_name}" != "" ]; then
    commit_message=$(head -1 $1 | grep -E "^${COMMIT_PREFIX}[-_][0-9]+ ")
    if [ "${commit_message}" = "" ]; then
        echo "WARNING!!! The commit message should be of the format '${branch_name} <Commit Message>'."
        exec < /dev/tty
        read -p "Do you still want to commit? (y/Y/n/N) " opt
        if [ "${opt}" = 'n' ] || [ "${opt}" = 'N' ]; then
            echo "Aborting !!"
            exit 1
        fi
    fi
fi
