# Generated by Django 2.0.2 on 2018-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content_file', models.FileField(upload_to='', verbose_name='File')),
                ('updated_time', models.DateTimeField(help_text='Date & Time when the content was updated recently', verbose_name='Content updated on')),
                ('last_uploaded_time', models.DateTimeField(editable=False, help_text='Date & Time when the file was updated recently', verbose_name='Last updated on')),
                ('checksum', models.SlugField(editable=False, help_text='SHA256 Sum of the file uploaded recently.', max_length=65, verbose_name='SHA256 Sum')),
            ],
        ),
    ]
