# Generated by Django 2.0.2 on 2018-03-01 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(to='content_management.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tags', to='content_management.Tag'),
        ),
    ]
