# Generated by Django 2.0.2 on 2018-03-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_auto_20180306_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorylayout',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directorylayout',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
