# Generated by Django 2.0.2 on 2018-03-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_directory_layout_field_name_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dir_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='content_management.DirectoryLayout'),
        ),
    ]
