# Generated by Django 2.0.2 on 2018-04-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_auto_20180330_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='directorylayout',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='filtercriteria',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['pk']},
        ),
    ]
