# Generated by Django 2.0.2 on 2018-04-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_auto_20180401_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='filter_criteria',
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='directory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.Directory'),
        ),
    ]
