# Generated by Django 2.0.2 on 2018-04-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_auto_20180402_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercriteria',
            name='directory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_criteria', to='content_management.Directory'),
        ),
    ]
