# Generated by Django 2.0.2 on 2018-04-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_auto_20180402_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='individual_files',
            field=models.ManyToManyField(related_name='individual_files', to='content_management.Content'),
        ),
    ]
