# Generated by Django 2.0.2 on 2018-04-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0011_directory_individual_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cataloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='filtercriteria',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='filtercriteria',
            name='left_criteria',
        ),
        migrations.RemoveField(
            model_name='filtercriteria',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='filtercriteria',
            name='right_criteria',
        ),
        migrations.RemoveField(
            model_name='filtercriteria',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.DeleteModel(
            name='FilterCriteria',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='content',
            name='cataloger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Cataloger'),
        ),
        migrations.AddField(
            model_name='content',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Coverage'),
        ),
        migrations.AddField(
            model_name='content',
            name='creators',
            field=models.ManyToManyField(to='content_management.Creator'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.ManyToManyField(to='content_management.Keyword'),
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Language'),
        ),
        migrations.AddField(
            model_name='content',
            name='subjects',
            field=models.ManyToManyField(to='content_management.Subject'),
        ),
        migrations.AddField(
            model_name='content',
            name='workareas',
            field=models.ManyToManyField(to='content_management.Workarea'),
        ),
    ]
