# Generated by Django 2.0.2 on 2018-04-12 01:16

import content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0014_auto_20180409_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorylayout',
            name='banner_file',
            field=models.FileField(default='', upload_to=content_management.models.DirectoryLayout.set_original_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directorylayout',
            name='original_file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
