# Generated by Django 2.0.2 on 2018-04-12 03:38

import content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0015_auto_20180411_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='banner_file',
            field=models.FileField(default='', upload_to=content_management.models.Directory.set_original_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='original_file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
