# Generated by Django 2.0.2 on 2018-04-13 01:04

import content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0016_auto_20180411_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='banner_file',
            field=models.FileField(null=True, upload_to=content_management.models.Directory.set_original_name),
        ),
    ]
