# Generated by Django 2.0.2 on 2018-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0017_auto_20180412_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='catalogers_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='coverages_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='creators_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='keywords_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='languages_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='subjects_need_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='workareas_need_all',
            field=models.BooleanField(default=True),
        ),
    ]
