# Generated by Django 2.0.2 on 2018-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0018_auto_20180415_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='last_uploaded_time',
            field=models.DateTimeField(editable=False, help_text='Date & Time when the file was uploaded', verbose_name='Last updated on'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_time',
            field=models.DateField(help_text='Date when the content was last updated', verbose_name='Content updated on'),
        ),
    ]
