# Generated by Django 2.0.2 on 2018-04-18 22:44

import content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0019_auto_20180416_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='original_file_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(upload_to=content_management.models.Content.set_original_name, verbose_name='File'),
        ),
    ]
