# Generated by Django 2.0.2 on 2018-04-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0021_auto_20180418_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.IntegerField(choices=[(1, 'Running'), (2, 'Finished')])),
                ('build_url', models.CharField(max_length=400, null=True)),
                ('completion_state', models.IntegerField(choices=[(1, 'Success'), (2, 'Failure')], null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('dir_layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.DirectoryLayout')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
