# Generated by Django 2.0.2 on 2018-04-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0022_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='build_url',
            new_name='build_file',
        ),
    ]
